---
name: Build and Deploy
on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - run: mkdir staging && cp target/*-standalone.jar staging
      - uses: actions/upload-artifact@v7
        with:
          name: dirsearch
          path: staging
      - name: Log in to the Container registry
        uses: docker/login-action@e46b7e330016f4e853155db7dd370d6b3d4fbdf5
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@85e876bd3a78bcc6b9925c818c482e365cf13b71
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@e25db879d025485a4eebd64fea9bb88a43632da6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
