---
name: Build and Deploy
on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - run: mkdir staging && cp target/*-standalone.jar staging
      - uses: actions/upload-artifact@v7
        with:
          name: dirsearch
          path: staging
      - name: Log in to the Container registry
        uses: docker/login-action@de05a6d3a24346d4659bce540fac29c04a309bad
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@12e32e61d3439d838b9b6d3fda7d2f6a422f893d
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@b66d8774c665b789105b440514f0c97e6f19b06f
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
